[package]
name = "dtig"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = { version = "0.29.0", features = ["all-widgets", "crossterm"] }
git2 = "0.20.2"

[dev-dependencies]
tempfile = "3.10.1"
